SET NAMES utf8mb4;
UPDATE `locations` SET `location_name` = 'Aalborg SV', `location_address` = 'Otto Mønsteds Vej 5' WHERE `location_id` = '1033';
UPDATE `locations` SET `location_name` = 'Aalborg SØ' WHERE `location_id` = '1029';
UPDATE `locations` SET `location_address` = 'Vestergårdsvej 3' WHERE `location_id` = '1041';
UPDATE `locations` SET `location_address` = 'Gammel Køge Landevej 690' WHERE `location_id` = '1043';
UPDATE `locations` SET `location_address` = 'Færgevejen 3' WHERE `location_id` = '1015';
UPDATE `locations` SET `location_address` = 'Sædding Ringvej 6' WHERE `location_id` = '1037';
UPDATE `locations` SET `location_address` = 'Gammelgårdsvej 84' WHERE `location_id` = '1021';
UPDATE `locations` SET `location_name` = 'Hjørring' WHERE `location_id` = '1062';
UPDATE `locations` SET `location_name` = 'Helsingør' WHERE `location_id` = '1051';
UPDATE `locations` SET `location_address` = 'Dæmningen 21' WHERE `location_id` = '1039';
UPDATE `locations` SET `location_name` = 'Frederiksværk' WHERE `location_id` = '1068';
UPDATE `locations` SET `location_address` = 'Sprogøvej 2' WHERE `location_id` = '1034';
UPDATE `locations` SET `location_name` = 'Højbjerg' WHERE `location_id` = '1065';
UPDATE `locations` SET `location_name` = 'Ishøj' WHERE `location_id` = '1063';
UPDATE `locations` SET `location_address` = 'Holbækvej 74' WHERE `location_id` = '1055';
UPDATE `locations` SET `location_name` = 'Køge', `location_address` = 'Københavnsvej 86' WHERE `location_id` = '1058';
UPDATE `locations` SET `location_address` = 'Lægårdsvej 4' WHERE `location_id` = '1046';
UPDATE `locations` SET `location_name` = 'Nykøbing Falster', `location_address` = 'Løjtoftevej 6' WHERE `location_id` = '1067';
UPDATE `locations` SET `location_name` = 'Næstved' WHERE `location_id` = '1022';
UPDATE `locations` SET `location_name` = 'Næstved Vest' WHERE `location_id` = '1023';
UPDATE `locations` SET `location_name` = 'Brønderslev' WHERE `location_id` = '1061';
UPDATE `locations` SET `location_name` = 'Odense SØ' WHERE `location_id` = '1018';
UPDATE `locations` SET `location_address` = 'Ørbækvej 99' WHERE `location_id` = '1072';
UPDATE `locations` SET `location_name` = 'Randers NØ' WHERE `location_id` = '1009';
UPDATE `locations` SET `location_address` = 'Trojels Knæ 6' WHERE `location_id` = '1057';
UPDATE `locations` SET `location_address` = 'Nørregade 70' WHERE `location_id` = '1019';
UPDATE `locations` SET `location_name` = 'Skive', `location_address` = 'Øster Fælled vej 4' WHERE `location_id` = '1070';
UPDATE `locations` SET `location_name` = 'Sorø', `location_address` = 'Idagårdsvej 2' WHERE `location_id` = '1006';
UPDATE `locations` SET `location_name` = 'Sorø Øst' WHERE `location_id` = '1005';
UPDATE `locations` SET `location_name` = 'Ringsted Øst' WHERE `location_id` = '1008';
UPDATE `locations` SET `location_name` = 'Tønder' WHERE `location_id` = '1020';
UPDATE `locations` SET `location_address` = 'Østerbakken 111' WHERE `location_id` = '1054';
